# Generated by Django 2.1.7 on 2019-04-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parame', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parame',
            new_name='Sheet',
        ),
    ]
