# Generated by Django 2.1.7 on 2019-04-09 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parame', '0002_auto_20190408_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='parame.Project'),
        ),
    ]
