# Generated by Django 2.1.7 on 2019-04-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parame', '0003_sheet_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='owner',
            field=models.IntegerField(default=1),
        ),
    ]
