# Generated by Django 2.1.7 on 2019-04-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parame', '0004_sheet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.IntegerField(default=1),
        ),
    ]
