# Generated by Django 2.1.7 on 2019-04-20 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parame', '0005_project_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='sheets',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='parame.Sheet'),
        ),
    ]
