# Generated by Django 2.1.7 on 2019-04-20 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parame', '0006_auto_20190420_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sheets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parame.Sheet'),
        ),
    ]
