# Generated by Django 2.1.7 on 2019-04-21 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parame', '0007_auto_20190420_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sheets',
        ),
        migrations.AddField(
            model_name='sheet',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='parame.Project'),
        ),
    ]
